name: JMeter Performance Tests

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger the workflow for PRs targeting 'main'

jobs:
  run-jmeter-tests:
    runs-on: ubuntu-latest  # The environment your jobs will run on

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout your repository's code

      - name: Set up JDK (if needed, for JMeter)
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # You can change this depending on your JMeter version requirements

      - name: Install JMeter
        run: |
          sudo apt-get update
          sudo apt-get install -y apache-jmeter  # Install JMeter on the VM

      - name: Run JMeter Tests
        run: |
          jmeter -n -t blazedemo.jmx -l blazedemoresult.jtl -e -o blazedemoReport  # Running JMeter test with the paths you provided

      - name: Upload JMeter Test Results
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-results
          path: blazedemoReport  # Upload JMeter report output folder

      - name: Publish JMeter Results (Optional)
        run: |
          echo "JMeter Results are available at:"
          echo "blazedemoReport/index.html"  # Path to view the JMeter HTML report
